name: Infrastructure Plan (Prod)

on:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]

jobs:
  terraform-plan-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    defaults:
      run:
        working-directory: ./infra
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      run: terraform init
    
    - name: Select Prod Workspace
      run: terraform workspace select prod
    
    - name: Terraform Plan (Prod Only)
      run: terraform plan -no-color
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    
    - name: Plan Summary
      run: |
        echo "✅ Terraform plan completed for PROD environment"
        echo "🔗 Review and apply manually at: https://app.terraform.io/"
        echo "📋 Workspace: prod"
