name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

env:
  TF_VERSION: '1.13.1'

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      working-directory: ./infra
      run: terraform init
    
    - name: Select Workspace
      working-directory: ./infra
      run: terraform workspace select ${{ matrix.environment }}
    
    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -var="environment=${{ matrix.environment }}"
      env:
        TF_VAR_environment: ${{ matrix.environment }}
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./infra
      run: terraform apply -auto-approve -var="environment=${{ matrix.environment }}"
      env:
        TF_VAR_environment: ${{ matrix.environment }}
