name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-deploy:
    if: needs.release-please.outputs.release_created
    needs: release-please
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, production]
    environment: ${{ matrix.environment }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Publish Function App
      run: dotnet publish src/Functions/ --configuration Release --output ./publish
    
    - name: Deploy to Azure Functions (Dev)
      if: matrix.environment == 'development'
      uses: Azure/functions-action@v1
      with:
        app-name: 'vjs-pension-dev-func'
        package: './publish'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}

    - name: Deploy to Azure Functions (Prod)
      if: matrix.environment == 'production'
      uses: Azure/functions-action@v1
      with:
        app-name: 'vjs-pension-prod-func'
        package: './publish'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}